---

- hosts: compute_vrouter,compute_vrouter-2,compute_mv_vrouter,compute_vepc,compute_vims,compute_vbng
  gather_facts: True
  strategy: free
  vars:
   - log_dir: "/tmp"
   - postfix: "contrail_snapshot.txt"
   - log_file: "{{ansible_hostname}}-{{postfix}}"

  tasks:
    - name: Arrange for intial setup i.e directory on compute
      file:
        path: /etc/ansible/facts.d/
        state: directory
        owner: heat-admin
        group: heat-admin
        mode: 0775

    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d%H-%M"
      register: tstamp
      delegate_to: localhost

    - name: Set date variables
      set_fact:
       cur_date: "{{ tstamp.stdout[0:10]}}"
       cur_time: "{{ tstamp.stdout}}"


    - name: Adding a magic stone to the pot
      copy:
       src: contrail_compute_snapshot.fact
       dest: /etc/ansible/facts.d/contrail_compute_snapshot.fact
       mode: 0755


    - name: Getting the stone soup on table
      fetch:
       src: "{{log_dir}}/{{log_file}}"
       dest: /home/stack/juniper_workspace/contrail_compute_scan-{{ cur_time }}/{{ log_file }}
       flat: yes
